services:
  frontend: 
    container_name: frontend-docker
    build: ./Frontend 
    ports: 
      - "3000:3000" 
    volumes:
      - ./Frontend/:/home/app/frontend
      - /home/app/frontend/node_modules/
      
  backend:
    container_name: backend-docker
    build: ./Backend
    ports:
      - "5000:5000"
    volumes:
      - ./Backend/:/home/app/backend
      - /home/app/backend/node_modules/
    depends_on:
      - db

  db:
    image: postgres:11.6-alpine
    ports:
      - "5432:5432"
    container_name: database-docker
    volumes:
      - app-data:/var/lib/postgresql/data

volumes:
  app-data:
    driver: local
